[GTM-1224] Error message when invalid email id used to book an appointment
thalmic/booking-js pull request #6
Opened 2019-09-25 16:01 UTC by mousaabynorth

2019-10-08 17:55 UTC, RBowering requested changes

2019-10-08 17:55 UTC, RBowering commented on src/render.js
> +          formElement.find('.input-email').addClass('error');
You don't need to do the find twice. You can either assign the input to a variable and use that variable twice, or just chain everything together like so:
```
formElement.find('.input-email')
    .addClass('error')
    .after('<div class="email-error">Please enter a valid email.</div>');
```

2019-10-12 21:07 UTC, lrezek approved these changes

2019-10-12 21:11 UTC, lrezek approved these changes

2019-10-12 21:11 UTC, merged

2025-01-24 21:28 UTC, TUMFILLAF17 approved these changes